import 'dart:typed_data';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

import '../../core/app_colors.dart';
import '../../data/download_service.dart';
import '../../shared/app_toast.dart';

/// One table block in an exported routine (header row + body rows).
class GridSection {
  final String? label;
  final List<String> headers;
  final List<List<String>> rows;
  final int todayIndex; // body-row index to highlight, or -1
  final List<double>? flex; // optional per-column flex weights
  const GridSection({
    this.label,
    required this.headers,
    required this.rows,
    this.todayIndex = -1,
    this.flex,
  });
}

/// Builds a clean tabular PDF (full content, no screenshot) for a routine, then
/// lets the user save it as a PDF or a PNG image — the app equivalent of the
/// website's "Download PDF / Image" buttons.
class RoutineExport {
  static const _green = PdfColor.fromInt(0xFF10B981);
  static const _grey = PdfColor.fromInt(0xFF6B7280);
  static const _line = PdfColor.fromInt(0xFFCBD5E1);
  static const _headBg = PdfColor.fromInt(0xFFEFF2F7);
  static const _todayBg = PdfColor.fromInt(0xFFE7F8F1);

  static Future<Uint8List> buildPdf({
    required String title,
    required String subtitle,
    required List<GridSection> sections,
    bool landscape = true,
  }) async {
    final doc = pw.Document();
    doc.addPage(
      pw.MultiPage(
        pageFormat: landscape ? PdfPageFormat.a4.landscape : PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(24),
        build: (ctx) => [
          pw.Text(title, style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 3),
          pw.Text(subtitle, style: const pw.TextStyle(fontSize: 9, color: _grey)),
          pw.SizedBox(height: 12),
          for (final s in sections) ...[
            if (s.label != null) ...[
              pw.Text(s.label!, style: pw.TextStyle(fontSize: 11, fontWeight: pw.FontWeight.bold, color: _green)),
              pw.SizedBox(height: 5),
            ],
            _table(s),
            pw.SizedBox(height: 16),
          ],
          pw.SizedBox(height: 6),
          pw.Text('Generated by CSE 62B Portal · lucse62b.xyz',
              style: const pw.TextStyle(fontSize: 8, color: _grey)),
        ],
      ),
    );
    return doc.save();
  }

  static pw.Widget _table(GridSection s) {
    final colWidths = <int, pw.TableColumnWidth>{};
    if (s.flex != null) {
      for (var i = 0; i < s.flex!.length; i++) {
        colWidths[i] = pw.FlexColumnWidth(s.flex![i]);
      }
    }
    return pw.Table(
      border: pw.TableBorder.all(color: _line, width: 0.5),
      columnWidths: colWidths.isEmpty ? null : colWidths,
      defaultVerticalAlignment: pw.TableCellVerticalAlignment.middle,
      children: [
        pw.TableRow(
          decoration: const pw.BoxDecoration(color: _headBg),
          children: [for (final h in s.headers) _cell(h, header: true)],
        ),
        for (var i = 0; i < s.rows.length; i++)
          pw.TableRow(
            decoration: i == s.todayIndex ? const pw.BoxDecoration(color: _todayBg) : null,
            children: [for (final c in s.rows[i]) _cell(c)],
          ),
      ],
    );
  }

  static pw.Widget _cell(String text, {bool header = false}) => pw.Padding(
        padding: const pw.EdgeInsets.symmetric(horizontal: 5, vertical: 5),
        child: pw.Text(
          text,
          textAlign: pw.TextAlign.center,
          style: pw.TextStyle(
            fontSize: header ? 8.5 : 8,
            fontWeight: header ? pw.FontWeight.bold : pw.FontWeight.normal,
            color: header ? _grey : PdfColors.black,
            lineSpacing: 1,
          ),
        ),
      );

  /// Show the Download PDF / Image sheet and save+open the chosen format.
  static Future<void> showSheet(
    BuildContext context, {
    required String baseName,
    required String title,
    required String subtitle,
    required List<GridSection> sections,
    bool landscape = true,
  }) async {
    final choice = await showModalBottomSheet<String>(
      context: context,
      backgroundColor: AppColors.card,
      shape: const RoundedRectangleBorder(borderRadius: BorderRadius.vertical(top: Radius.circular(20))),
      builder: (ctx) => SafeArea(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            const SizedBox(height: 12),
            Container(width: 40, height: 4, decoration: BoxDecoration(color: AppColors.border, borderRadius: BorderRadius.circular(2))),
            const Padding(
              padding: EdgeInsets.fromLTRB(18, 16, 18, 6),
              child: Align(
                alignment: Alignment.centerLeft,
                child: Text('Download routine',
                    style: TextStyle(color: AppColors.textBright, fontSize: 16, fontWeight: FontWeight.w700)),
              ),
            ),
            ListTile(
              leading: const Icon(Icons.picture_as_pdf_rounded, color: Color(0xFFF87171)),
              title: const Text('Download as PDF', style: TextStyle(color: AppColors.text)),
              onTap: () => Navigator.pop(ctx, 'pdf'),
            ),
            ListTile(
              leading: const Icon(Icons.image_rounded, color: Color(0xFF34D399)),
              title: const Text('Download as Image', style: TextStyle(color: AppColors.text)),
              onTap: () => Navigator.pop(ctx, 'image'),
            ),
            const SizedBox(height: 10),
          ],
        ),
      ),
    );
    if (choice == null || !context.mounted) return;

    AppToast.show(context, 'Preparing ${choice == 'pdf' ? 'PDF' : 'image'}…');
    try {
      final pdfBytes = await buildPdf(title: title, subtitle: subtitle, sections: sections, landscape: landscape);
      DownloadEntry? ent;
      if (choice == 'pdf') {
        ent = await DownloadService.instance.saveBytes('gen_$baseName', '$baseName.pdf', pdfBytes,
            mime: 'application/pdf', source: 'Routine');
      } else {
        final raster = await Printing.raster(pdfBytes, pages: [0], dpi: 200).first;
        final png = await raster.toPng();
        ent = await DownloadService.instance.saveBytes('gen_${baseName}_img', '$baseName.png', png,
            mime: 'image/png', source: 'Routine');
      }
      if (!context.mounted) return;
      if (ent != null) {
        AppToast.show(context, 'Saved · opening…');
        await DownloadService.instance.open(ent.fileId);
      } else {
        AppToast.show(context, 'Could not save the file.');
      }
    } catch (_) {
      if (context.mounted) AppToast.show(context, 'Export failed. Please try again.');
    }
  }

  // ── Pixel-faithful export: capture a print template widget → PNG / PDF ──

  /// Capture [child] (laid out at its natural size) to a PNG off-screen, so the
  /// downloaded image/PDF looks exactly like the website's rendered template.
  static Future<({Uint8List png, int width, int height})?> _capture(
      BuildContext context, Widget child, {double pixelRatio = 2}) async {
    final overlay = Overlay.of(context, rootOverlay: true);
    final key = GlobalKey();
    final entry = OverlayEntry(
      builder: (_) => Positioned(
        left: 0,
        top: -1000000, // off-screen but still painted
        child: Material(
          type: MaterialType.transparency,
          child: Directionality(
            textDirection: TextDirection.ltr,
            child: RepaintBoundary(key: key, child: child),
          ),
        ),
      ),
    );
    overlay.insert(entry);
    try {
      // Let it lay out, paint, and load fonts/glyphs.
      await Future.delayed(const Duration(milliseconds: 90));
      await WidgetsBinding.instance.endOfFrame;
      final ro = key.currentContext?.findRenderObject();
      if (ro is! RenderRepaintBoundary) return null;
      final image = await ro.toImage(pixelRatio: pixelRatio);
      final data = await image.toByteData(format: ui.ImageByteFormat.png);
      if (data == null) return null;
      return (png: data.buffer.asUint8List(), width: image.width, height: image.height);
    } catch (_) {
      return null;
    } finally {
      entry.remove();
    }
  }

  static Future<Uint8List> _pngToPdf(({Uint8List png, int width, int height}) cap) async {
    final doc = pw.Document();
    final img = pw.MemoryImage(cap.png);
    // Mirror the website (jsPDF): page sized to the image (÷3) with a 10pt margin.
    final w = cap.width / 3.0, h = cap.height / 3.0;
    doc.addPage(pw.Page(
      pageFormat: PdfPageFormat(w + 20, h + 20),
      margin: const pw.EdgeInsets.all(10),
      build: (ctx) => pw.Image(img, width: w, height: h),
    ));
    return doc.save();
  }

  /// Download a print-template [build] widget as a PDF or image (website-exact).
  static Future<void> showImageSheet(
    BuildContext context, {
    required String baseName,
    required Widget Function() build,
  }) async {
    final choice = await _pickFormat(context);
    if (choice == null || !context.mounted) return;
    AppToast.show(context, 'Preparing ${choice == 'pdf' ? 'PDF' : 'image'}…');
    try {
      final cap = await _capture(context, build());
      if (cap == null) {
        if (context.mounted) AppToast.show(context, 'Could not render the routine.');
        return;
      }
      DownloadEntry? ent;
      if (choice == 'image') {
        ent = await DownloadService.instance.saveBytes('gen_${baseName}_img', '$baseName.png', cap.png,
            mime: 'image/png', source: 'Routine');
      } else {
        final pdf = await _pngToPdf(cap);
        ent = await DownloadService.instance.saveBytes('gen_$baseName', '$baseName.pdf', pdf,
            mime: 'application/pdf', source: 'Routine');
      }
      if (!context.mounted) return;
      if (ent != null) {
        AppToast.show(context, 'Saved · opening…');
        await DownloadService.instance.open(ent.fileId);
      } else {
        AppToast.show(context, 'Could not save the file.');
      }
    } catch (_) {
      if (context.mounted) AppToast.show(context, 'Export failed. Please try again.');
    }
  }

  /// The shared "Download as PDF / Image" chooser sheet.
  static Future<String?> _pickFormat(BuildContext context) {
    return showModalBottomSheet<String>(
      context: context,
      backgroundColor: AppColors.card,
      shape: const RoundedRectangleBorder(borderRadius: BorderRadius.vertical(top: Radius.circular(20))),
      builder: (ctx) => SafeArea(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            const SizedBox(height: 12),
            Container(width: 40, height: 4, decoration: BoxDecoration(color: AppColors.border, borderRadius: BorderRadius.circular(2))),
            const Padding(
              padding: EdgeInsets.fromLTRB(18, 16, 18, 6),
              child: Align(
                alignment: Alignment.centerLeft,
                child: Text('Download routine',
                    style: TextStyle(color: AppColors.textBright, fontSize: 16, fontWeight: FontWeight.w700)),
              ),
            ),
            ListTile(
              leading: const Icon(Icons.picture_as_pdf_rounded, color: Color(0xFFF87171)),
              title: const Text('Download as PDF', style: TextStyle(color: AppColors.text)),
              onTap: () => Navigator.pop(ctx, 'pdf'),
            ),
            ListTile(
              leading: const Icon(Icons.image_rounded, color: Color(0xFF34D399)),
              title: const Text('Download as Image', style: TextStyle(color: AppColors.text)),
              onTap: () => Navigator.pop(ctx, 'image'),
            ),
            const SizedBox(height: 10),
          ],
        ),
      ),
    );
  }
}
